# Generated by Django 5.2.7 on 2025-10-02 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("doc_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="uploaded", max_length=50)),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("topic_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("page_start", models.IntegerField()),
                ("page_end", models.IntegerField()),
                ("prerequisites", models.JSONField(default=list)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "doc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="textbooks.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                ("chunk_id", models.AutoField(primary_key=True, serialize=False)),
                ("page_id", models.IntegerField()),
                ("start_offset", models.IntegerField()),
                ("end_offset", models.IntegerField()),
                ("text", models.TextField()),
                ("embedding_id", models.CharField(max_length=255, null=True)),
                (
                    "doc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="textbooks.document",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="textbooks.topic",
                    ),
                ),
            ],
        ),
    ]
