# Generated by Django 5.2.7 on 2025-10-05 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textbooks", "0002_alter_document_status_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chunk",
            name="end_offset",
        ),
        migrations.RemoveField(
            model_name="chunk",
            name="page_id",
        ),
        migrations.RemoveField(
            model_name="chunk",
            name="start_offset",
        ),
        migrations.AlterField(
            model_name="chunk",
            name="embedding_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="chunk",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="textbooks.topic",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="doc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="textbooks.document",
            ),
        ),
        migrations.CreateModel(
            name="SubTopic",
            fields=[
                ("subtopic_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("page_start", models.IntegerField(blank=True, null=True)),
                ("page_end", models.IntegerField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtopics",
                        to="textbooks.topic",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chunk",
            name="subtopic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="textbooks.subtopic",
            ),
        ),
    ]
